typedef Iterables           = stx.Iterables; //Must go first for Arrays to overload functions to more specific type
typedef Arrays              = stx.Arrays;
typedef Bools               = stx.Bools;
typedef Dates               = stx.Dates;
typedef Dynamics            = stx.Dynamics;
typedef Eithers             = stx.Eithers;
typedef Enums               = stx.Enums;
typedef CodeBlocks          = stx.Functions.CodeBlocks;
typedef Functions0          = stx.Functions.Functions0;
typedef Functions1          = stx.Functions.Functions1;
typedef Functions2          = stx.Functions.Functions2;
typedef Functions3          = stx.Functions.Functions3;
typedef Functions4          = stx.Functions.Functions4;
typedef Functions5          = stx.Functions.Functions5;
typedef Functions6          = stx.Functions.Functions6;
typedef Future<T>           = stx.Future<T>;
typedef Hashes              = stx.Hashes;
typedef Iterators           = stx.Iterators;
typedef Log                 = stx.Log;
typedef Maths               = stx.Maths;
typedef Objects             = stx.Objects;
typedef Options             = stx.Options;
typedef Predicates          = stx.Predicates;
typedef Promises            = stx.Promises;
typedef Strings             = stx.Strings;

typedef Equal 							= stx.plus.Equal;

typedef Show 								= stx.plus.Show;
typedef Order 							= stx.plus.Order;
typedef Hasher 							= stx.plus.Hasher;